trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ShareMyCalendar.API

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: 'ShareMyCalendar.API/ShareMyCalendar.API.csproj'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish $(buildConfiguration)'
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration)'
    publishWebProjects: false
    projects: 'ShareMyCalendar.API/ShareMyCalendar.API.csproj'
