trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    projects: 'ShareMyCalendar.API.csproj'
    workingDirectory: 'ShareMyCalendar.API'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: 'ShareMyCalendar.API.csproj'
    workingDirectory: 'ShareMyCalendar.API'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'ShareMyCalendar.API.csproj'
    workingDirectory: 'ShareMyCalendar.API'