trigger:
  branches:
    include:
      - main
  paths:
    include:
      - ShareMyCalendar.API

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    projects: '.'
    workingDirectory: 'ShareMyCalendar.API'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '.'
    workingDirectory: 'ShareMyCalendar.API'
- task: DotNetCoreCLI@2
  displayName: 'dotnet publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '.'
    workingDirectory: 'ShareMyCalendar.API'